apiVersion: v1
kind: Service
metadata:
  name: app-2048-service
  namespace: app-2048
spec:
  selector:
    app: app-2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer